import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..");
const wasmPath = resolve(root, "playground/public/restty.wasm");
const outPath = resolve(root, "src/wasm/embedded.ts");

const bytes = await readFile(wasmPath);
const b64 = Buffer.from(bytes).toString("base64");
const wrapped = b64.match(/.{1,120}/g)?.join("\n") ?? b64;
const content =
  "// Auto-generated by embed script.\n" +
  "// Source: playground/public/restty.wasm\n" +
  `export const WASM_BASE64 = \`\n${wrapped}\n\`\n`;

await writeFile(outPath, content, "utf-8");
console.log(`Embedded wasm -> ${outPath}`);
