import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const wasmDir = resolve(root, "wasm");
const builtWasmPath = resolve(wasmDir, "zig-out/bin/restty.wasm");
const embeddedWasmPath = resolve(root, "src/wasm/embedded.ts");
const wasmOptimizeMode = process.env.RESTTY_WASM_OPTIMIZE?.trim() || "ReleaseSafe";

function makeCommandEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (value !== undefined) env[key] = value;
  }
  return env;
}

function commandOutput(command: string[], cwd: string): string | null {
  const proc = Bun.spawnSync(command, {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  });

  if (proc.exitCode !== 0) return null;
  return Buffer.from(proc.stdout).toString("utf-8").trim();
}

function encodeWasmBinaryLiteral(bytes: Uint8Array): string {
  let output = "";

  for (let i = 0; i < bytes.length; i += 1) {
    const byte = bytes[i];
    const next = bytes[i + 1];
    const shouldHexEscape =
      byte < 0x20 || byte === 0x7f || (byte >= 0x80 && byte <= 0x9f);

    if (byte === 0x5c) {
      output += "\\\\";
    } else if (byte === 0x60) {
      output += "\\`";
    } else if (byte === 0x24 && next === 0x7b) {
      output += "\\$";
    } else if (byte === 0x0a) {
      output += "\\n";
    } else if (byte === 0x0d) {
      output += "\\r";
    } else if (byte === 0x09) {
      output += "\\t";
    } else if (shouldHexEscape) {
      output += `\\x${byte.toString(16).padStart(2, "0")}`;
    } else {
      output += String.fromCharCode(byte);
    }
  }

  return output;
}

function prepareDarwinBuild(env: Record<string, string>): void {
  if (process.platform !== "darwin") return;

  const sdkVersion = commandOutput(["xcrun", "--sdk", "macosx", "--show-sdk-version"], root);
  const sdkMajor = Number.parseInt(sdkVersion?.split(".")[0] ?? "", 10);
  if (sdkMajor >= 27 && !process.env.RESTTY_WASM_HOST_DEVELOPER_DIR) {
    // Zig 0.15.2 links the build runner incorrectly when it autodetects the
    // macOS 27 SDK. wasm/build.zig retargets build-time tools after startup.
    env.DEVELOPER_DIR = "/__restty_no_xcode_sdk_autodetect__";
  } else if (process.env.RESTTY_WASM_HOST_DEVELOPER_DIR?.trim()) {
    env.DEVELOPER_DIR = process.env.RESTTY_WASM_HOST_DEVELOPER_DIR.trim();
  }
}

function runCommand(command: string[], cwd: string, env: Record<string, string>): void {
  const proc = Bun.spawnSync(command, {
    cwd,
    env,
    stdio: ["ignore", "inherit", "inherit"],
  });

  if (proc.exitCode !== 0) {
    process.exit(proc.exitCode ?? 1);
  }
}

console.log("Building wasm module...");
const buildEnv = makeCommandEnv();
const buildCommand = [
  "zig",
  "build",
  "-Dtarget=wasm32-freestanding",
  `-Doptimize=${wasmOptimizeMode}`,
];
prepareDarwinBuild(buildEnv);
runCommand(buildCommand, wasmDir, buildEnv);

console.log("Regenerating src/wasm/embedded.ts...");
const bytes = await readFile(builtWasmPath);
const binary = encodeWasmBinaryLiteral(bytes);
const content =
  "// Auto-generated by build:wasm script.\n" +
  "// Source: wasm/zig-out/bin/restty.wasm\n" +
  `// Zig optimize mode: ${wasmOptimizeMode}\n` +
  "// The string stores byte values directly to compress better than base64.\n" +
  `export const WASM_BINARY: string = \`${binary}\`;\n`;
await writeFile(embeddedWasmPath, content, "utf-8");

console.log("WASM build and embed refresh complete.");
