import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type ThemeManifest = {
  themes?: unknown;
};

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const themesDir = resolve(root, "assets/themes");
const manifestPath = resolve(themesDir, "manifest.json");
const outPath = resolve(root, "src/theme/builtin-themes.ts");

const manifestRaw = await readFile(manifestPath, "utf8");
const manifest = JSON.parse(manifestRaw) as ThemeManifest;
if (!Array.isArray(manifest.themes)) {
  throw new Error("Invalid theme manifest: expected { themes: string[] }");
}

const names = manifest.themes.map((name) => String(name));
const entries: Array<{ name: string; source: string }> = [];

for (const name of names) {
  const path = resolve(themesDir, name);
  const source = await readFile(path, "utf8");
  entries.push({ name, source });
}

const namesJson = JSON.stringify(names, null, 2);
const sourceLines = entries.map(({ name, source }) => {
  return `  ${JSON.stringify(name)}: ${JSON.stringify(source)},`;
});

const content = [
  "// Auto-generated by scripts/generate-builtin-themes.ts",
  "// Do not edit by hand.",
  "",
  `export const BUILTIN_THEME_NAMES = ${namesJson} as const;`,
  "",
  "export type BuiltinThemeName = (typeof BUILTIN_THEME_NAMES)[number];",
  "",
  "export const BUILTIN_THEME_SOURCES: Record<BuiltinThemeName, string> = {",
  ...sourceLines,
  "};",
  "",
].join("\n");

await writeFile(outPath, content, "utf8");
console.log(`Wrote ${outPath} (${entries.length} themes)`);
